version: '3.7'
services: 
    servicio-config-server:
        image: servicio-config-server:v1
        ports: 
            - "8888:8888"
        restart: always
        networks: 
          - springcloud
    servicio-eureka-server:
        image: servicio-eureka-server:v1
        ports: 
          - "8761:8761"
        restart: always
        networks: 
          - springcloud
networks: 
    springcloud: